const express = require('express');
const axios = require('axios');
const db = require('./db');
const app = express();
const port = 3000;

// Middleware to parse JSON requests
app.use(express.json());

// DeepSeek API endpoint and key
const deepSeekApiUrl = 'https://api.deepseek.ai/v1/ask'; // Replace with actual DeepSeek API URL
const apiKey = 'your_deepseek_api_key'; // Replace with your DeepSeek API key

// Function to call DeepSeek API and get SQL query and natural language response
async function getSqlAndNaturalLanguageResponse(question) {
  try {
    // Make a POST request to DeepSeek API with the question
    const response = await axios.post(deepSeekApiUrl, {
      query: question,
      key: apiKey
    });

    // Get the SQL query generated by DeepSeek
    const sqlQuery = response.data.sqlQuery;

    // Return both the SQL query and the natural language response
    return { sqlQuery, naturalLanguageResponse: response.data.answer };
  } catch (error) {
    console.error('Error calling DeepSeek API:', error);
    return { sqlQuery: null, naturalLanguageResponse: 'Error processing the question' };
  }
}

// Define route for handling queries
app.post('/query', async (req, res) => {
  const { question } = req.body; // Question from user

  // Get SQL query and natural language response from DeepSeek
  const { sqlQuery, naturalLanguageResponse } = await getSqlAndNaturalLanguageResponse(question);

  if (sqlQuery) {
    // If SQL query is generated, execute it on the MySQL database
    db.query(sqlQuery, (err, results) => {
      if (err) {
        console.error('Error querying MySQL:', err);
        return res.status(500).json({ error: 'Database error' });
      }

      // Process the results (you can do further formatting here)
      const finalResponse = naturalLanguageResponse.replace('{result}', JSON.stringify(results));

      // Send the natural language response to the user
      res.status(200).json({ response: finalResponse });
    });
  } else {
    // If no SQL query is generated, return an error response
    res.status(500).json({ error: 'Unable to process the question' });
  }
});

// Start the server
app.listen(port, () => {
  console.log(`Server running at http://localhost:${port}`);
});

/* How It Works:
DeepSeek API Call:

When you ask a question (e.g., "What is the total sales for 2025?"), the DeepSeek API generates both an SQL query (e.g., SELECT total_sales FROM sales WHERE year = 2025) and a natural language response (e.g., "The total sales for 2025 are...").
MySQL Query Execution:

The generated SQL query is executed on your MySQL database using the mysql2 package.
Result Processing:

The result from MySQL is then injected into the natural language response from DeepSeek. For example, if the query returns a total sales value of $1,000,000, the final response might be: "The total sales for 2025 is $1,000,000."
Postman Testing:

You can send the following POST request to http://localhost:3000/query with the question in the request body: */